//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuningAtelier.ENT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BatteriesEntities : DbContext
    {
        public BatteriesEntities()
            : base("name=BatteriesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batteriesBucket> batteriesBucket { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<statusOrder> statusOrder { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<userGenders> userGenders { get; set; }
        public virtual DbSet<userRoles> userRoles { get; set; }
        public virtual DbSet<userStatus> userStatus { get; set; }
    }
}
