//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuningAtelier.ENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class batteriesBucket
    {
        public int idBucket { get; set; }
        public int idOrder { get; set; }
        public int idBatteries { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual order order { get; set; }
    }
}
