//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuningAtelier.ENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.batteriesBucket = new HashSet<batteriesBucket>();
        }
    
        public int idOrder { get; set; }
        public int idUser { get; set; }
        public Nullable<int> idShop { get; set; }
        public string status { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public System.DateTime orderDate { get; set; }
        public System.TimeSpan orderTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batteriesBucket> batteriesBucket { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual statusOrder statusOrder { get; set; }
        public virtual user user { get; set; }
    }
}
